package tools

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"io"
	"maps"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"gopkg.in/yaml.v3"

	mcpgrafana "github.com/grafana/mcp-grafana"
)

const grafanaSampleDatasourcesURL = "https://raw.githubusercontent.com/grafana/grafana/refs/heads/main/conf/provisioning/datasources/sample.yaml"

type parsedSample struct {
	apiVersion   int
	baseTemplate map[string]any
}

var (
	sampleOnce sync.Once
	sampleCache parsedSample
)

// uncommentYAML strips the leading "# " from commented-out lines in Grafana's
// sample YAML files, making them parseable as regular YAML.
func uncommentYAML(s string) string {
	lines := strings.Split(s, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		switch {
		case strings.HasPrefix(line, "# "):
			out = append(out, line[2:])
		case line == "#":
			out = append(out, "")
		default:
			out = append(out, line)
		}
	}
	return strings.Join(out, "\n")
}

// loadSample fetches the Grafana sample datasource YAML once per process and
// returns the parsed apiVersion and a base field template for new entries.
// Falls back to safe defaults if the fetch fails.
func loadSample() parsedSample {
	sampleOnce.Do(func() {
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()

		req, err := http.NewRequestWithContext(ctx, http.MethodGet, grafanaSampleDatasourcesURL, nil)
		if err != nil {
			return
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return
		}

		var pf datasourceProvisioningFile
		if err := yaml.Unmarshal([]byte(uncommentYAML(string(body))), &pf); err != nil {
			return
		}

		// always honor the API version that comes from the sample RAW github file.
		sampleCache.apiVersion = pf.APIVersion

		// Build a base template from the first datasource entry, keeping only the
		// non-null fields that are common to all types. Skip name, type, uid, and
		// url since those are always provided by the caller or left out intentionally.
		// Clear jsonData/secureJsonData since their contents are type-specific.
		if len(pf.Datasources) > 0 {
			skip := map[string]bool{"name": true, "type": true, "uid": true, "url": true}
			tmpl := make(map[string]any)
			for k, v := range pf.Datasources[0] {
				if v == nil || skip[k] {
					continue
				}
				if k == "jsonData" || k == "secureJsonData" {
					tmpl[k] = map[string]any{}
					continue
				}
				tmpl[k] = v
			}
			sampleCache.baseTemplate = tmpl
		}
	})
	
	return sampleCache
}

type datasourceProvisioningFile struct {
	APIVersion  int              `yaml:"apiVersion"`
	Datasources []map[string]any `yaml:"datasources"`
}

type ProvisionDatasourceParams struct {
	Directory   string `json:"directory,omitempty" jsonschema:"description=Directory where the tool will attempt to write the YAML provisioning file. Optional. Writing to disk is only reliable when the server is running via stdio (local mode). In remote deployments the write targets the server's filesystem\\, not the client's — omit this and use the returned content and zip_content instead."`
	FileName    string `json:"file_name,omitempty" jsonschema:"description=Template for the file name. Supports {type} placeholder. Defaults to 'prov-{type}'."`
	Type        string `json:"type" jsonschema:"required,description=Datasource type (e.g. prometheus\\, loki\\, influxdb)"`
	Name        string `json:"name,omitempty" jsonschema:"description=Datasource display name. Derived from file name template if omitted."`
	URL         string `json:"url,omitempty" jsonschema:"description=Datasource connection URL (e.g. http://prometheus:9090)"`
	IsDefault   bool   `json:"isDefault,omitempty" jsonschema:"description=Set as the default datasource for the Grafana instance"`
	UID         string `json:"uid,omitempty" jsonschema:"description=Unique identifier for the datasource. Auto-generated by Grafana if omitted."`
	ForceUpdate bool   `json:"force_update,omitempty" jsonschema:"description=If true\\, overwrite an existing datasource entry with the same name. Defaults to false\\, which returns a conflict error instead."`
}

type ProvisionDatasourceResult struct {
	FilePath    string `json:"file_path,omitempty"`
	FileCreated bool   `json:"file_created,omitempty"`
	Conflict    bool   `json:"conflict,omitempty"`
	Content     string `json:"content"`
	ZipContent  string `json:"zip_content"`
	Summary     string `json:"summary"`
}

// buildZip produces a base64-encoded zip archive from a map of filename -> content.
func buildZip(files map[string][]byte) (string, error) {
	var buf bytes.Buffer
	zw := zip.NewWriter(&buf)
	for name, content := range files {
		w, err := zw.Create(name)
		if err != nil {
			return "", err
		}
		if _, err := w.Write(content); err != nil {
			return "", err
		}
	}
	if err := zw.Close(); err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(buf.Bytes()), nil
}

// stemToDisplayName converts a stem like "my-prometheus" to "My Prometheus".
func stemToDisplayName(stem string) string {
	parts := strings.FieldsFunc(stem, func(r rune) bool {
		return r == '-' || r == '_'
	})
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, " ")
}

func provisionDatasource(_ context.Context, args ProvisionDatasourceParams) (*ProvisionDatasourceResult, error) {
	s := loadSample()

	fileName := args.FileName
	if fileName == "" {
		fileName = "prov-{type}"
	}
	stem := strings.ReplaceAll(fileName, "{type}", args.Type)

	dsName := args.Name
	if dsName == "" {
		dsName = stemToDisplayName(stem)
	}

	// Load existing file if a directory was given, otherwise start fresh.
	pf := &datasourceProvisioningFile{APIVersion: s.apiVersion}
	isNew := true
	var filePath string

	if args.Directory != "" {
		filePath = filepath.Join(args.Directory, stem+".yaml")
		if data, err := os.ReadFile(filePath); err == nil {
			isNew = false
			if err := yaml.Unmarshal(data, pf); err != nil {
				return nil, fmt.Errorf("parse %s: %w", filePath, err)
			}
		} else if !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", filePath, err)
		}
	}

	// Only set fields the user explicitly provided so that unrecognised
	// fields in an existing entry (e.g. basicAuth, jsonData) are preserved.
	updates := map[string]any{
		"name": dsName,
		"type": args.Type,
	}
	if args.URL != "" {
		updates["url"] = args.URL
		updates["access"] = "proxy"
	}
	if args.UID != "" {
		updates["uid"] = args.UID
	}
	if args.IsDefault {
		updates["isDefault"] = true
	}

	// Upsert: merge into existing entry by name, or append.
	upserted := false
	for i, existing := range pf.Datasources {
		if existing["name"] == dsName {
			if !args.ForceUpdate {
				return &ProvisionDatasourceResult{
					FilePath: filePath,
					Conflict: true,
					Summary:  fmt.Sprintf("Datasource '%s' already exists in %s. Set force_update to true to overwrite it, or provide a different name.", dsName, filePath),
				}, nil
			}
			maps.Copy(existing, updates)
			pf.Datasources[i] = existing
			upserted = true
			break
		}
	}
	if !upserted {
		// For new entries, start from the sample base template so the output
		// reflects the current Grafana provisioning schema, then overlay user values.
		base := make(map[string]any, len(s.baseTemplate))
		maps.Copy(base, s.baseTemplate)
		maps.Copy(base, updates)
		pf.Datasources = append(pf.Datasources, base)
	}

	out, err := yaml.Marshal(pf)
	if err != nil {
		return nil, fmt.Errorf("marshal YAML: %w", err)
	}
	content := string(out)

	zipContent, err := buildZip(map[string][]byte{stem + ".yaml": out})
	if err != nil {
		return nil, fmt.Errorf("build zip: %w", err)
	}

	// Write to disk only when a directory was provided.
	if args.Directory != "" {
		if err := os.MkdirAll(args.Directory, 0755); err != nil {
			return nil, fmt.Errorf("create directory %s: %w", args.Directory, err)
		}
		if err := os.WriteFile(filePath, out, 0644); err != nil {
			return nil, fmt.Errorf("write %s: %w", filePath, err)
		}
	}

	var summary string
	if args.Directory == "" {
		summary = fmt.Sprintf("Generated provisioning YAML for datasource '%s'. The content and zip_content fields contain the result — extract zip_content into your local provisioning/datasources directory.", dsName)
	} else {
		action := "update"
		if isNew {
			action = "create"
		}
		summary = fmt.Sprintf("Attempted to %s provisioning file %s with datasource '%s'. Write to disk is only guaranteed when running via stdio — in remote mode this targeted the server's filesystem.", action, filePath, dsName)
	}

	return &ProvisionDatasourceResult{
		FilePath:    filePath,
		FileCreated: isNew && args.Directory != "",
		Content:     content,
		ZipContent:  zipContent,
		Summary:     summary,
	}, nil
}

var ProvisionDatasource = mcpgrafana.MustTool(
	"provision_datasource",
	"Generate a Grafana datasource provisioning YAML file. The schema is fetched from Grafana's official sample at startup so the output always reflects the current provisioning format. Always returns the YAML content and a base64-encoded zip archive. Optionally attempts to write to disk when a directory is provided — only reliable when running via stdio (local mode). In remote deployments use the returned content or zip_content to save the file locally.",
	provisionDatasource,
	mcp.WithTitleAnnotation("Provision datasource"),
)

func AddDatasourceProvisioningTools(mcp *server.MCPServer) {
	ProvisionDatasource.Register(mcp)
}
